[BitTorrent]
Session\Port=6881

[LegalNotice]
Accepted=true

[Preferences]
WebUI\Enabled=true
WebUI\Port=44011
WebUI\Address=*
WebUI\LocalHostAuth=false
WebUI\HostHeaderValidation=false
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\SecureCookie=true
WebUI\Username=admin
WebUI\Password_PBKDF2=@ByteArray(d0ec493d27ed22320ed7846f37f7cb7c:8110294c441dca8054cc5c36b00017327be671af0b6c91ed8e59188b85eb0e03cbc02c02eb161c413e66fdb2ca49703ca55b4090dce302c0adbfc8a7f64f15a1)
